version: "3.8"

services:
  server:
    build: ./server
    container_name: media_server
    ports:
      - "9001:9001"
    volumes:
      - ./server/processed:/app/processed  

  client:
    build: ./client
    container_name: media_client
    ports:
      - "8501:8501"         
    depends_on:
      - server
