name: Docker Compose Build and Startup Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-start:
    name: Build and Start Containers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # リポジトリのコードを取得する

      - name: Build containers
        run: docker compose build  # ビルド（docker compose build）

      - name: Start containers
        run: docker compose up -d  # 起動（docker compose up -d）

      - name: Wait and check running containers
        run: |
          sleep 5
          docker ps                # 起動後に動作しているか確認（docker ps）
          docker compose ps        # コンテナの状態確認（docker compose ps）

      - name: Stop containers
        run: docker compose down   # 終了処理（docker compose down）
